### ISSUE TITLE
Objective-To-Do List

### ISSUE THREAD

**Issue by jaweber** [AndrewScibek/RaiderPlate#2]
Add or edit anything you feel is appropriate or necessary. 

- [ ] Interview at least THREE users who are not taking CS4366. Be specific on the users, for example range of age, culture, computer/IT experience, attitude, and anything you may think important. Prepare several questions and log entire interviews (1 or 2 pages) and summarize them (2 or 3 paragraph). 

1. Complete a set of interview questions.
2. Interview at least 3 people not in Senior Capstone.

- [ ] Identify the existing functions and suggest new functions and their features. List all the functions that your system should support. Explain as detail as possible, for example, function environment, constraint, trade-off, and anything you may think important. 

1. Functional Requirements.
2. Non-functional requirements
3. Constraints
4. 

- [ ] Consider any data requirement and data input/output of your system.  
- [ ] Refer to IEEE Std 830-1998 (IEEE Recommended Practice for Software Requirements Specifications
